import picrossLevelBib

""" Spiel-Settings """
FENSTERBREITE = 1300
FENSTERHOEHE = 1000
ANZAHLREIHEN = 10
ANZAHLSPALTEN = 10
SCHWIERIGKEIT = -1000


ZUFAELLIGESLEVEL = picrossLevelBib.zufaelligesLevelMitSchwierigkeit(ANZAHLSPALTEN, ANZAHLREIHEN, SCHWIERIGKEIT)
VORGEFERTIGTESLEVEL = picrossLevelBib.nummer04

LEVEL = VORGEFERTIGTESLEVEL
